# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 06:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='RegUser',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Regular users',
                'verbose_name': 'Regular user',
                'proxy': True,
            },
            bases=('auth.user',),
        ),
        migrations.CreateModel(
            name='SysAdminUser',
            fields=[
            ],
            options={
                'verbose_name_plural': 'System administrators',
                'verbose_name': 'System administrator',
                'proxy': True,
            },
            bases=('auth.user',),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
