# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 09:20
from __future__ import unicode_literals

from django.db import migrations, models

import users.models
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, storage=users.storage.OverwriteStorage(), upload_to=users.models.get_profile_image_filename),
        ),
    ]
