# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20161207_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='security_question_answer',
            field=models.TextField(null=True, verbose_name='security question answer'),
        ),
    ]
