# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20161207_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gaid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Google Analytics ID'),
        ),
    ]
