# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_profile_gaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Google Analytics ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gaid',
        ),
    ]
