# -*- coding: utf-8 -*-
# Generated by Chad Garrett on 2017-09-04 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations

from users.models import EndlineSurveySelectUsers


def link_user_endline(apps, schema_editor):
    """Link all existing users to an Endline Survey opportunity. New users get linked through a signal"""
    if schema_editor.connection.alias != 'default':
        return

    users = User.objects.all()
    for user in users:
        EndlineSurveySelectUsers.objects.get_or_create(user=user, receive_survey=False, survey_completed=False)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_endlinesurveyselectusers'),
    ]

    operations = [
        migrations.RunPython(link_user_endline),
    ]
