# -*- coding: utf-8 -*-
# Generated by Chad Garrett on 2017-09-04 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def link_user_endline(apps, schema_editor):
    """Link all existing users to an Endline Survey opportunity. New users get linked through a signal"""
    if schema_editor.connection.alias != 'default':
        return

    User = apps.get_model('auth', 'User')
    EndlineSurveySelectUsers = apps.get_model('users', 'EndlineSurveySelectUsers')

    users = User.objects.all()
    for user in users:
        EndlineSurveySelectUsers.objects.get_or_create(user=user)


def noop(apps, schema_editor):
    """"Since this migration only ensures that the linking model exists, we're not going to bother to delete them."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_endlinesurveyselectusers'),
    ]

    operations = [
        migrations.RunPython(link_user_endline, noop),
    ]
