# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_endline_selected_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endlinesurveyselectusers',
            name='user',
        ),
        migrations.DeleteModel(
            name='EndlineSurveySelectUsers',
        ),
    ]
