sudo: false
language: python
python:
  - "3.4"
  - "3.5"
before_script:
  - ./setuptests.sh
install:
  - "pip install -r requirements.txt --use-wheel"
script:
  - python manage.py migrate
  - python manage.py test
cache:
  directories:
- $HOME/.cache/pip
