# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20161221_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachsurvey',
            name='deliver_after',
            field=models.PositiveIntegerField(default=1, help_text='The number of days after user registration that the Survey will be available.', verbose_name='days to deliver'),
        ),
    ]
