# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 08:28
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_coachsurveysubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='survey.CoachSurvey'),
        ),
    ]
