# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_submission_historic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachformfield',
            name='key',
            field=models.CharField(blank=True, help_text="Field identifier. Warning: Changing this will prevent existing submissions' fields from being exported.", max_length=30, verbose_name='key'),
        ),
    ]
