# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_coachformfield_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachformfield',
            name='key',
            field=models.CharField(blank=True, help_text="Field identifier. Warning: Changing this will prevent existing submissions' fields from being exported.", max_length=255, verbose_name='key'),
        ),
    ]
