# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_coachformfield_key_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsurvey',
            name='notification_body',
            field=models.TextField(blank=True, help_text='The content body of the first Survey notification the user receives.', verbose_name='notification body'),
        ),
        migrations.AddField(
            model_name='coachsurvey',
            name='reminder_notification_body',
            field=models.TextField(blank=True, help_text='The content body of the repeating Survey notifications the user receives.', verbose_name='reminder notification body'),
        ),
    ]
