# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_coachsurveyindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsurveysubmission',
            name='age',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='coachsurveysubmission',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachsurveysubmission',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='coachsurveysubmission',
            name='user_unique_id',
            field=models.IntegerField(default=-1),
        ),
    ]
