# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_coachsurveysubmissiondraft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachsurveysubmissiondraft',
            options={'verbose_name': 'coach survey submission draft', 'verbose_name_plural': 'coach survey submission drafts'},
        ),
        migrations.AlterField(
            model_name='coachsurveysubmissiondraft',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='survey.CoachSurvey'),
        ),
    ]
