# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_coachsurveysubmissiondraft_rename_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsurveysubmissiondraft',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachsurveysubmissiondraft',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.CoachSurveySubmission'),
        ),
    ]
