# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_coachsurveysubmissiondraft_completing'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsurveysubmission',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='survey.CoachSurvey'),
        ),
    ]
