# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0019_auto_20170904_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndlineSurveySelectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_survey', models.BooleanField(default=False, help_text='Should the user receive the Endline Survey')),
                ('survey_completed', models.BooleanField(default=False, help_text='Has the user already completed the survey')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'endline survey selected user',
                'verbose_name_plural': 'endline survey selected users',
            },
        ),
    ]
