# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 08:49
from __future__ import unicode_literals

from django.db import migrations


def link_user_endline(apps, schema_editor):
    """Link all existing users to an Endline Survey opportunity. New users get linked through a signal"""
    if schema_editor.connection.alias != 'default':
        return

    User = apps.get_model('auth', 'User')
    EndlineSurveySelectUser = apps.get_model('survey', 'EndlineSurveySelectUser')

    users = User.objects.all()
    for user in users:
        EndlineSurveySelectUser.objects.get_or_create(user=user)


def noop(apps, schema_editor):
    """"Since this migration only ensures that the linking model exists, we're not going to bother to delete them."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_endlinesurveyselectuser'),
    ]

    operations = [
        migrations.RunPython(link_user_endline, noop),
    ]
