# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Challenge Name')),
                ('activation_date', models.DateTimeField(verbose_name='Activate On')),
                ('deactivation_date', models.DateTimeField(verbose_name='Deactivate On')),
                ('state', models.PositiveIntegerField(choices=[(0, 'Incomplete'), (1, 'Ready for review'), (2, 'Published'), (3, 'Done')], default=0, verbose_name='State')),
                ('end_processed', models.BooleanField(default=False, verbose_name='Processed')),
            ],
        ),
    ]
