# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.URLField(null=True, verbose_name='Picture URL')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Multiple choice'), (2, 'Freeform'), (3, 'Picture')], default=2, verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'verbose_name': 'Question',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.URLField(null=True, verbose_name='Picture URL')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Question')),
            ],
            options={
                'verbose_name_plural': 'Options',
                'verbose_name': 'Option',
            },
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'verbose_name': 'Challenge', 'verbose_name_plural': 'Challenges'},
        ),
        migrations.AlterField(
            model_name='challenge',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Incomplete'), (2, 'Ready for review'), (3, 'Published'), (4, 'Done')], default=1, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='question',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Challenge'),
        ),
    ]
