# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20161005_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'verbose_name': 'Question Option', 'verbose_name_plural': 'Question Options'},
        ),
    ]
