# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20161027_1309'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop),
    ]
