# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20161005_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.URLField(blank=True, null=True, verbose_name='Picture URL'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='picture',
            field=models.URLField(blank=True, null=True, verbose_name='Picture URL'),
        ),
    ]
