# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_tag_tip_squashed_0006_auto_20161011_1314'),
    ]

    operations = [
        migrations.RenameModel('Question', 'QuizQuestion'),
        migrations.AlterField(
            model_name='QuestionOption',
            name='next_question',
            field=models.ForeignKey('QuizQuestion', blank=False, null=True, related_name='+'),
        ),
        migrations.AlterField(
            model_name='AnswerLog',
            name='question',
            field=models.ForeignKey('QuizQuestion', blank=False, null=True, related_name='+'),
        ),
    ]
