# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_tag_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Tag')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('content.tag', models.Model),
        ),
        migrations.RemoveField(
            model_name='tip',
            name='tags',
        ),
        migrations.AddField(
            model_name='tiptag',
            name='tip',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='content.Tip'),
        ),
    ]
