# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('content', '0005_questionoption_correct'),
    ]

    dependencies = {
        ('content', '0004_question_to_quizquestion_b'),
    }

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='correct'),
        ),
    ]
