# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20161005_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.DateTimeField(verbose_name='Answered On')),
                ('saved', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Saved On')),
                ('user', models.TextField(blank=True, verbose_name='Text')),
                ('response', models.TextField(blank=True, verbose_name='Text')),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Challenge')),
            ],
            options={
                'verbose_name_plural': 'User Answers',
                'verbose_name': 'User Answer Log',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.TextField(blank=True, unique=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='name',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='answerlog',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.Question'),
        ),
    ]
