# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('content', '0005_remove_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_tiptag_items', to='taggit.Tag')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_item', to='content.Tip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tip',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='content.TipTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
