# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.Challenge'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.Question'),
        ),
    ]
