# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20161028_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='name',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='next_question',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='name',
        ),
    ]
