# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20161028_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'goal',
                'verbose_name_plural': 'goals'
            },
        ),
        migrations.CreateModel(
            name='GoalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Goal')),
            ],
            options={
                'verbose_name': 'goal transaction',
                'verbose_name_plural': 'goal transactions',
            },
        ),
    ]
