# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 06:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('content', '0009_goal'), ('content', '0010_goal_user'), ('content', '0011_auto_20161031_1506'), ('content', '0012_auto_20161102_1519')]

    dependencies = [
        ('content', '0008_auto_20161028_1115'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'goals',
                'verbose_name': 'goal',
            },
        ),
        migrations.CreateModel(
            name='GoalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='content.Goal')),
            ],
            options={
                'verbose_name_plural': 'goal transactions',
                'verbose_name': 'goal transaction',
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(),
        ),
    ]
