# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 08:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0008_auto_20161028_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='created on')),
                ('date_completed', models.DateTimeField(null=True, verbose_name='completed on')),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='content.Challenge')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'participant',
                'verbose_name_plural': 'participants',
            },
        ),
        migrations.RemoveField(
            model_name='participantanswer',
            name='user',
        ),
        migrations.AlterField(
            model_name='participantanswer',
            name='date_saved',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='saved on'),
        ),
        migrations.AddField(
            model_name='participantanswer',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.Participant'),
        ),
    ]
