# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20161031_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTextQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('challenge', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freetext_question', to='content.Challenge')),
            ],
            options={
                'verbose_name_plural': 'free text questions',
                'verbose_name': 'free text question',
            },
        ),
        migrations.CreateModel(
            name='PictureQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('challenge', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture_question', to='content.Challenge')),
            ],
            options={
                'verbose_name_plural': 'picture questions',
                'verbose_name': 'picture question',
            },
        ),
    ]
