# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_goal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goaltransaction',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='content.Goal'),
        ),
    ]
