# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_freetextquestion_picturequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantFreeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('date_answered', models.DateTimeField(verbose_name='answered on')),
                ('date_saved', models.DateTimeField(default=datetime.datetime.now, verbose_name='saved on')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freetext_answer', to='content.Participant')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.FreeTextQuestion')),
            ],
            options={
                'verbose_name_plural': 'free-text answers',
                'verbose_name': 'free-text answer',
            },
        ),
        migrations.CreateModel(
            name='ParticipantPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('date_answered', models.DateTimeField(verbose_name='answered on')),
                ('date_saved', models.DateTimeField(default=datetime.datetime.now, verbose_name='saved on')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture_answer', to='content.Participant')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.PictureQuestion')),
            ],
            options={
                'verbose_name_plural': 'picture answers',
                'verbose_name': 'picture answer',
            },
        ),
    ]
