# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_goal_squashed_0012_auto_20161102_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_saved',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='saved on'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='participantanswer',
            name='date_saved',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='saved on'),
        ),
        migrations.AlterField(
            model_name='participantfreetext',
            name='date_saved',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='saved on'),
        ),
        migrations.AlterField(
            model_name='participantpicture',
            name='date_saved',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='saved on'),
        ),
    ]
