# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 13:47
from __future__ import unicode_literals

import content.models
import content.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20161103_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=content.storage.GoalImgStorage(), upload_to=content.models.get_goal_image_filename),
        ),
    ]
