# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 09:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0016_tipfavourite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipfavourite',
            unique_together=set([('user', 'tip')]),
        ),
    ]
