# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20161105_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipfavourite',
            name='date_favourited',
        ),
    ]
