# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_remove_tipfavourite_date_favourited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipfavourite',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='content.Tip'),
        ),
    ]
