# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_transaction_datetime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goaltransaction',
            unique_together=set([('date', 'value', 'goal')]),
        ),
    ]
