# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_unique_together_goal_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='value',
            new_name='target',
        ),
        migrations.AlterField(
            model_name='goal',
            name='target',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
