# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20161104_0815'),
        ('content', '0022_rename_value_to_target'),
    ]

    operations = [
    ]
