# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_merge_20161112_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='hint',
            field=models.TextField(blank=True, verbose_name='hint'),
        ),
    ]
