# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_quizquestion_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='hint',
            field=models.TextField(blank=True, null=True, verbose_name='hint'),
        ),
    ]
