# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 12:11
from __future__ import unicode_literals

import content.models
import content.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_challenge_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=content.storage.ChallengeStorage(), upload_to=content.models.get_challenge_image_filename, verbose_name='picture'),
        ),
    ]
