# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 11:25
from __future__ import unicode_literals

import content.models
import content.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20161114_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantpicture',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=content.storage.ParticipantPictureStorage(), upload_to=content.models.get_participant_image_filename, verbose_name='picture'),
        ),
    ]
