# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('content', '0029_auto_20161117_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'agreements',
                'verbose_name': 'agreement',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ChallengeAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Agreement')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Challenge')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='agreement',
            field=models.ManyToManyField(through='content.ChallengeAgreement', to='content.Agreement'),
        ),
    ]
