# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 11:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_tip_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='challenge',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.Challenge'),
        ),
    ]
