# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 16:44
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_challenge_wagtail_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.QuizQuestion'),
        ),
    ]
