# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_remove_participant_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='call_to_action',
            field=models.CharField(blank=True, help_text='Displayed on the Challenge popup when it is not available yet.', max_length=200, verbose_name='call to action'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='instruction',
            field=models.CharField(blank=True, help_text='Displayed on the Challenge splash screen when it is available.', max_length=200, verbose_name='instructional text'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='intro',
            field=models.CharField(blank=True, help_text='The opening line said by the Coach when telling the user about the Challenge.', max_length=200, verbose_name='intro dialogue'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='outro',
            field=models.CharField(blank=True, help_text='The line said by the Coach when the user has completed their Challenge submission.', max_length=200, verbose_name='outro dialogue'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='subtitle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tip',
            name='intro',
            field=models.CharField(blank=True, help_text='The opening line said by the Coach when telling the user about the Tip.', max_length=200, verbose_name='intro dialogue'),
        ),
    ]
