# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_add_challenge_instructional_ui_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeagreement',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='challengeagreement',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='agreement',
        ),
        migrations.AddField(
            model_name='challenge',
            name='terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.Agreement'),
        ),
        migrations.DeleteModel(
            name='ChallengeAgreement',
        ),
    ]
