# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_challenge_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content.Agreement'),
        ),
    ]
