# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_intro_fields_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(max_length=255, verbose_name='challenge name'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
