# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('content', '0041_challenge_titles_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'goal prototype',
                'verbose_name_plural': 'goal prototypes',
            },
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='goal',
            name='prototype',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='content.GoalPrototype'),
        ),
    ]
