# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_goal_prototype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalprototype',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
