# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_goal_default_prototype_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalprototype',
            name='state',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0),
        ),
    ]
