# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_challenge_subtitle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantpicture',
            name='date_answered',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='answered on'),
        ),
    ]
