# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_picture_participant_date_answered_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='prototype',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='content.GoalPrototype'),
        ),
    ]
