# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_prototype_fix_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='state',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
