# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('content', '0051_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_first_created', models.ForeignKey(help_text='Awarded to users when they create their first Goal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='First Goal Created')),
                ('goal_first_done', models.ForeignKey(help_text='Awarded to users when they reach their first Goal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='First Goal Done')),
                ('goal_half', models.ForeignKey(help_text='Awarded to users when they are half-way through their first Goal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='First Goal Done')),
                ('goal_week_left', models.ForeignKey(help_text='Awarded to users when they have one week left to save on their first Goal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='One Week Left')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
                ('transaction_first', models.ForeignKey(help_text='Awarded to users when they create their first savings transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='First Saving')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
