# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0054_userbadge_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgesettings',
            name='goal_half',
            field=models.ForeignKey(help_text='Awarded to users when they are half-way through their first Goal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='First Goal Half Way'),
        ),
    ]
