# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 08:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0055_badge_halfway_typo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2016, 12, 6, 8, 47, 3, 864730, tzinfo=utc), verbose_name='date created')),
                ('is_read', models.BooleanField(default=False, verbose_name='has been read')),
                ('text', models.TextField(verbose_name='text')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Ask a question'), (2, 'Report a problem'), (3, 'General feedback'), (4, 'Sponsorship and partnership requests')], verbose_name='type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'feedback entries',
                'verbose_name': 'feedback entry',
            },
        ),
    ]
