# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0057_auto_20161206_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgesettings',
            name='streak_2',
            field=models.ForeignKey(help_text='Awarded when a user has saved for 2 weeks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='2 Week Streak'),
        ),
        migrations.AddField(
            model_name='badgesettings',
            name='streak_4',
            field=models.ForeignKey(help_text='Awarded when a user has saved for 4 weeks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='4 Week Streak'),
        ),
        migrations.AddField(
            model_name='badgesettings',
            name='streak_6',
            field=models.ForeignKey(help_text='Awarded when a user has save for 6 weeks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='6 Week Streak'),
        ),
    ]
