# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('content', '0058_badge_week_streak'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_app_id', models.CharField(blank=True, help_text='The App Id provided by Facebook via the Developer Console.', max_length=255, verbose_name='Facebook App Id')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'social media accounts',
            },
        ),
        migrations.AlterModelOptions(
            name='badgesettings',
            options={'verbose_name': 'Badge Setup'},
        ),
    ]
