# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0059_socialmediasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='intro',
            field=models.TextField(blank=True, help_text='The opening line said by the Coach when presenting the user with their Badge.', verbose_name='intro dialogue'),
        ),
    ]
