# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0060_badge_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='badge-slug', help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/', max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
