# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0061_badge_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgesettings',
            name='challenge_entry',
            field=models.ForeignKey(help_text='Awarded when a user has participated in a Challenge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='Challenge Participation'),
        ),
        migrations.AddField(
            model_name='badgesettings',
            name='challenge_win',
            field=models.ForeignKey(help_text='Awarded when a user has won a Challenge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='Challenge Winner'),
        ),
        migrations.AddField(
            model_name='badgesettings',
            name='weekly_target_2',
            field=models.ForeignKey(help_text='Awarded when a user has reached their weekly target 2 weeks in a row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='2 Week On Target'),
        ),
        migrations.AddField(
            model_name='badgesettings',
            name='weekly_target_4',
            field=models.ForeignKey(help_text='Awarded when a user has reached their weekly target 4 weeks in a row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='4 Week On Target'),
        ),
        migrations.AddField(
            model_name='badgesettings',
            name='weekly_target_8',
            field=models.ForeignKey(help_text='Awarded when a user has reached their weekly target 6 weeks in a row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='6 Week On Target'),
        ),
    ]
