# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0065_badgesettings_first_challenge_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgesettings',
            name='first_challenge_completed',
        ),
        migrations.AddField(
            model_name='participant',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='is read'),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_shortlisted',
            field=models.BooleanField(default=False, verbose_name='is shortlisted'),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_winner',
            field=models.BooleanField(default=False, verbose_name='is winner'),
        ),
    ]
