# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0066_auto_20170124_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='badges',
            field=models.ManyToManyField(to='content.UserBadge'),
        ),
    ]
