# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0068_participant_has_been_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgesettings',
            name='first_challenge_completed',
            field=models.ForeignKey(help_text='Awarded when a user has completed their first challenge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='First Challenge Completed'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together=set([]),
        ),
    ]
