# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0071_userbadge_remove_constraint'),
        ('content', '0065_remove_delete_permission_for_challenge'),
    ]

    operations = [
    ]
