# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0065_change_badge_setting_from_8_to_6'),
        ('content', '0071_userbadge_remove_constraint'),
    ]

    operations = [
    ]
