# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0069_auto_20170127_1328'),
        ('content', '0072_merge_20170130_0936'),
    ]

    operations = [
    ]
