# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0072_merge_20170130_1101'),
        ('content', '0073_merge_20170131_0808'),
    ]

    operations = [
    ]
