# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 11:21

from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0074_merge_20170201_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgesettings',
            name='first_challenge_completed',
        ),
    ]
