# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0074_merge_20170201_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgesettings',
            name='first_challenge_completed',
        ),
        migrations.AddField(
            model_name='badge',
            name='prize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
