# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0075_auto_20170201_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='prize',
        ),
        migrations.AddField(
            model_name='challenge',
            name='prize',
            field=models.CharField(blank=True, default='none', max_length=255, verbose_name='challenge prize'),
        ),
    ]
