# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('content', '0076_goalprototype_default_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='The message to be displayed to the user')),
                ('publish_date', models.DateField(verbose_name='The date the notification should start displaying')),
                ('expiration_date', models.DateField(verbose_name='The date when the notification should stop displaying')),
                ('persist', models.BooleanField(verbose_name='Should the notification show every time the user opens the app, or just once?')),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
    ]
