# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0076_auto_20170201_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='prize',
        ),
        migrations.AddField(
            model_name='challenge',
            name='prize_day',
            field=models.CharField(blank=True, default='none', max_length=255, verbose_name='prize day'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='prize_name',
            field=models.CharField(blank=True, default='none', max_length=255, verbose_name='prize name'),
        ),
    ]
