# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0076_goalprototype_default_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantpicture',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='caption'),
        ),
    ]
