# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0077_auto_20170201_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='prize_day',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='prize_name',
        ),
        migrations.AddField(
            model_name='challenge',
            name='prize',
            field=models.CharField(blank=True, default='none', help_text='The text to be displayed to a user who wins a prize', max_length=255, verbose_name='prize'),
        ),
    ]
