# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0078_auto_20170214_0952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomNotifications',
            new_name='CustomNotification',
        ),
    ]
