# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0079_auto_20170214_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customnotification',
            name='persist',
        ),
        migrations.AlterField(
            model_name='customnotification',
            name='expiration_date',
            field=models.DateField(help_text='The date when the notification should stop displaying', verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='customnotification',
            name='publish_date',
            field=models.DateField(help_text='The date the notification should start displaying', verbose_name='publish date'),
        ),
    ]
