# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0080_auto_20170220_0757'),
        ('content', '0077_participantpicture_caption'),
    ]

    operations = [
    ]
