# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:49
from __future__ import unicode_literals

from math import ceil, floor

from django.db import migrations, models


class WeekCalc:

    @classmethod
    def week_diff(cls, from_date, to_date, rounding):
        if rounding == cls.Rounding.UP:
            return ceil((to_date - from_date).days / 7.0)
        elif rounding == cls.Rounding.DOWN:
            return floor((to_date - from_date).days / 7.0)
        else:
            return (to_date - from_date).days / 7.0

    @classmethod
    def day_diff(cls, from_date, to_date):
        return (to_date - from_date).days

    @classmethod
    def remainder(cls, from_date, to_date):
        """Calculates the remaining days after a week difference has been calculated and rounded down."""
        return cls.day_diff(from_date, to_date) - cls.week_diff(from_date, to_date, cls.Rounding.DOWN) * 7

    class Rounding:
        NONE = 0
        UP = 1
        DOWN = 2


def get_weeks(self):
    """The number of weeks from the start date to the end date."""
    return WeekCalc.week_diff(self.start_date, self.end_date, WeekCalc.Rounding.UP) or 1


def get_calculated_weekly_target(goal):
    weeks = get_weeks(goal)
    return goal.target if weeks == 0 else ceil(goal.target / weeks)


def set_weekly_target(apps, schema_editor):
    Goal = apps.get_model('content', 'Goal')
    for goal in Goal.objects.all().iterator():
        goal.weekly_target = get_calculated_weekly_target(goal)
        goal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0080_auto_20170220_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='weekly_target',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.RunPython(set_weekly_target),
        migrations.AlterField(
            model_name='goal',
            name='weekly_target',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
