# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0081_goal_weekly_target'),
        ('content', '0081_merge_20170227_1334'),
    ]

    operations = [
    ]
