# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0082_merge_20170227_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='prize',
            field=models.TextField(blank=True, help_text='Prize for winning a challenge.', verbose_name='prize'),
        ),
    ]
