# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0082_merge_20170227_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.QuizQuestion'),
        ),
    ]
