# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0082_merge_20170227_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'First Goal Created'), (2, 'First Goal Half Way'), (3, 'One Week Left'), (4, 'First Goal Done'), (5, 'First Saving'), (6, '2 Week Streak'), (7, '4 Week Streak'), (8, '6 Week Streak'), (9, '2 Week On Target'), (10, '4 Week On Target'), (11, '6 Week On Target'), (12, 'Challenge Participation'), (13, 'Challenge Winner')], default=0),
        ),
    ]
