# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0083_expensecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='income')),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='savings')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'budget',
                'verbose_name': 'budget',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='value')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('budget', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='content.Budget')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.ExpenseCategory')),
            ],
            options={
                'verbose_name_plural': 'expenses',
                'verbose_name': 'expense',
            },
        ),
    ]
