# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0083_challenge_prize'),
        ('content', '0084_budget_expense'),
    ]

    operations = [
    ]
