# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0084_auto_20170308_1202'),
        ('content', '0083_auto_20170309_1701'),
        ('content', '0083_badge_badge_type'),
        ('content', '0085_merge_20170313_0739'),
    ]

    operations = [
    ]
