# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0086_merge_20170314_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
