# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 11:51
from __future__ import unicode_literals

from django import VERSION as DJANGO_VERSION
from django.db import migrations


def add_reporters_group(apps, schema_editor):
    pass


def remove_reporters_group(apps, schema_editor):
    pass


def add_report_permissions(apps, schema_editor):
    ContentType = apps.get_model('contenttypes.ContentType')
    Permission = apps.get_model('auth.Permission')
    Group = apps.get_model('auth.Group')

    reporters_group, created = Group.objects.get_or_create(name='Reporters')

    # Fake content type
    reports_content_type, created = ContentType.objects.get_or_create(
        app_label='content',
        model='reports'
    )

    # Create reporter permission
    reporter_permission, created = Permission.objects.get_or_create(
        content_type=reports_content_type,
        codename='access_reports',
        name='Can access report exports'
    )

    # Assign it to Reporters group
    group = Group.objects.get(name='Reporters')
    group.permissions.add(reporter_permission)


def remove_report_permissions(apps, schema):
    """Reverse the above additions of permissions."""
    ContentType = apps.get_model('contenttypes.ContentType')
    Permission = apps.get_model('auth.Permission')

    reports_content_type = ContentType.objects.get(
        app_label='content',
        model='reports'
    )

    # Cascades to Group
    Permission.objects.filter(
        content_type=reports_content_type,
        codename='access_reports'
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0086_merge_20170314_0720'),
    ]

    operations = [
        migrations.RunPython(add_report_permissions,
                             remove_report_permissions),
    ]
