# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0087_expense_name_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='order',
            field=models.IntegerField(default=0, help_text='The order in which this category will appear on the frontend'),
        ),
    ]
