# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0088_expensecategory_order'),
        ('content', '0087_report_permissions'),
    ]

    operations = [
    ]
