# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 12:37
from __future__ import unicode_literals

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0090_budget_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='created_on',
            field=models.DateTimeField(default=content.models.datetime_default, editable=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_on',
            field=models.DateTimeField(default=content.models.datetime_default, editable=False),
        ),
    ]
