# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0091_datetime_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='expenses_decreased_count',
            new_name='expense_decreased_count',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='expenses_increased_count',
            new_name='expense_increased_count',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='expenses_modified',
            new_name='expense_modified',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='original_expenses',
            new_name='original_expense',
        ),
    ]
