# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0092_rename_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='modified_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
