# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0093_budget_modified_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='state',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
