# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0094_expense_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgesettings',
            name='budget_creation',
            field=models.ForeignKey(help_text='Awarded when a user has created a budget.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='Budget Creation'),
        ),
        migrations.AddField(
            model_name='badgesettings',
            name='budget_edit',
            field=models.ForeignKey(help_text='Awarded when a user has edited a budget.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Badge', verbose_name='Budget Edit'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'First Goal Created'), (2, 'First Goal Half Way'), (3, 'One Week Left'), (4, 'First Goal Done'), (5, 'First Saving'), (6, '2 Week Streak'), (7, '4 Week Streak'), (8, '6 Week Streak'), (9, '2 Week On Target'), (10, '4 Week On Target'), (11, '6 Week On Target'), (12, 'Challenge Participation'), (13, 'Challenge Winner'), (14, 'Budget Creation'), (15, 'Budget Edit')], default=0),
        ),
    ]
