# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-10 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0095_auto_20170408_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='initial_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
