# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0096_goal_initial_savings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'budget', 'verbose_name_plural': 'budgets'},
        ),
    ]
